import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion';
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUp, Maximize2, Minus, Plus } from 'lucide-react';
import './styles.css';

type Chapter = { eyebrow: string; title: React.ReactNode; body?: React.ReactNode; kicker?: string; visual: string };

const chapters: Chapter[] = [
  { eyebrow: 'Capital protegido para desenvolvimento de atletas', title: <>E se investir no futuro de um atleta também pudesse <em>começar a construir o patrimônio dele?</em></>, body: 'Uma nova arquitetura para desenvolvimento de atletas, proteção de capital e formação patrimonial.', visual: 'cover' },
  { eyebrow: '01 / A janela', title: <>A carreira esportiva tem uma <em>janela extraordinária</em> de geração de renda.</>, body: 'Essa janela tem prazo. O desafio é transformar capacidade esportiva em riqueza permanente.', visual: 'timeline' },
  { eyebrow: '02 / A assimetria', title: <>Renda cresce mais rápido do que a <em>estrutura financeira.</em></>, body: 'Renda não é patrimônio. O problema não é necessariamente má utilização. É ausência de arquitetura.', visual: 'orbit' },
  { eyebrow: '03 / A exposição', title: <>Quando todo o capital depende da mesma variável, o risco se torna <em>concentrado.</em></>, body: 'Talento, evolução, performance, mercado, contratos e trajetória profissional: a carreira.', visual: 'exposure' },
  { eyebrow: '04 / A pergunta', title: <>Se R$ 1 milhão será aplicado no desenvolvimento de um atleta, por que necessariamente todo ele precisa ficar exposto ao <em>mesmo tipo de risco?</em></>, visual: 'question' },
  { eyebrow: '05 / A arquitetura', title: <>Capital total. <em>Funções diferentes.</em></>, body: 'Desenvolver o atleta sem tratar todo o capital como recurso consumível.', visual: 'split' },
  { eyebrow: '06 / A ferramenta', title: <>O consórcio não é a tese. É uma das <em>ferramentas</em> da arquitetura.</>, body: 'Um mecanismo de aquisição patrimonial programada dentro de uma estratégia maior.', visual: 'tool' },
  { eyebrow: '07 / O exemplo', title: <>Uma estrutura ilustrativa para começar a <em>separar funções.</em></>, body: 'Percentuais não definitivos. A proporção depende do atleta, da carreira, do horizonte e do perfil.', visual: 'allocation' },
  { eyebrow: '08 / O que permanece', title: <>O jogador não termina o ciclo somente com uma história de renda passada.</>, body: 'O patrimônio reduz a dependência absoluta do próximo contrato.', visual: 'outcomes' },
  { eyebrow: '09 / Governança', title: <>Proteger capital não significa eliminar risco. Significa <em>estruturar melhor a exposição.</em></>, visual: 'beforeafter' },
  { eyebrow: '10 / Liberdade', title: <>Segurança financeira também pode gerar <em>liberdade profissional.</em></>, body: 'Patrimônio muda a forma como o atleta toma decisões.', visual: 'freedom' },
  { eyebrow: '11 / Acompanhamento', title: <>A arquitetura começa <em>antes</em> da transferência do capital.</>, body: 'Plano de capital, liberações programadas, prestação de contas e revisões periódicas.', visual: 'governance' },
  { eyebrow: '12 / A mudança', title: <>Não estamos tentando prever o futuro do atleta. Estamos tentando <em>estruturar melhor o capital</em> que financiará esse futuro.</>, visual: 'handoff' },
  { eyebrow: '13 / A métrica', title: <>Quanto da riqueza gerada durante a carreira conseguimos transformar em <em>patrimônio?</em></>, body: 'Índice de Patrimonialização do Atleta — uma metodologia a ser definida.', visual: 'index' },
  { eyebrow: '14 / Encerramento', title: <>A carreira de um atleta tem prazo. O patrimônio construído durante ela <em>não deveria ter.</em></>, body: 'Desenvolver o presente. Proteger o capital. Construir o depois.', visual: 'end' },
];

function Flow({ labels, mode = 'row' }: { labels: string[]; mode?: 'row' | 'stack' }) { return <div className={`flow ${mode}`}>{labels.map((label, i) => <React.Fragment key={label}><div className="flowNode">{label}</div>{i < labels.length - 1 && <div className="flowLine"><ArrowRight size={14}/></div>}</React.Fragment>)}</div> }
function Visual({ kind }: { kind: string }) {
  if (kind === 'cover') return <div className="coverMark"><span>CP</span><div className="coverRule"/><small>CAPITAL PROTEGIDO<br/>PARA DESENVOLVIMENTO<br/>DE ATLETAS</small></div>;
  if (kind === 'timeline') return <div className="timeline"><div className="timelineLine"/><div className="timelinePoints">{['Ascensão','Alta performance','Consolidação','Transição'].map((x, i) => <div key={x} className="point"><i style={{ animationDelay: `${i * .18}s` }}/><span>{x}</span><b>0{i + 1}</b></div>)}</div></div>;
  if (kind === 'orbit') return <div className="orbit"><div className="orbitRing r1"/><div className="orbitRing r2"/><div className="orbitCenter">RENDA<br/><span>≠</span><br/>PATRIMÔNIO</div><div className="orbitLabel l1">Moradia</div><div className="orbitLabel l2">Família</div><div className="orbitLabel l3">Imagem</div></div>;
  if (kind === 'exposure') return <div className="exposure"><div className="capital">R$ CAPITAL</div><div className="down">↓</div><div className="athlete">ATLETA</div><div className="down">↓</div><div className="expect">EXPECTATIVA DE<br/><strong>VALORIZAÇÃO FUTURA</strong></div><span className="sideNote">100% do capital exposto<br/>ao mesmo ativo: a carreira.</span></div>;
  if (kind === 'question') return <div className="questionVisual"><div className="bigR">R$ 1M</div><div className="questionSlash">/</div><div><div className="tinyLabel">MESMO CAPITAL</div><div className="questionWords">CARREIRA<br/><span>+ proteção<br/>+ patrimônio</span></div></div></div>;
  if (kind === 'split') return <div className="splitVisual"><div className="splitTotal"><span>CAPITAL<br/>TOTAL</span><strong>R$</strong></div><div className="splitBar"><i/><i/><i/></div><div className="splitLegend"><span><b>60%</b> desenvolvimento</span><span><b>30%</b> patrimonialização</span><span><b>10%</b> contingência</span></div></div>;
  if (kind === 'tool') return <Flow labels={['Capital patrimonial','Estratégia programada','Aquisição','Ativos','Patrimônio']} />;
  if (kind === 'allocation') return <div className="allocation"><div><strong>R$ 1 MM</strong><span>capital total</span></div><div className="allocRows"><span><b>R$ 600 mil</b> desenvolvimento</span><span><b>R$ 300 mil</b> estrutura patrimonial</span><span><b>R$ 100 mil</b> liquidez / contingência</span></div></div>;
  if (kind === 'outcomes') return <div className="outcomes">{[['01','Se a carreira explode','A estrutura patrimonial já começou.'],['02','Se evolui moderadamente','Existe patrimônio paralelo.'],['03','Se decepciona','Nem todo o capital termina em consumo.']].map(([n,t,d]) => <div key={n} className="outcome"><b>{n}</b><strong>{t}</strong><span>{d}</span></div>)}</div>;
  if (kind === 'beforeafter') return <div className="beforeAfter"><div><small>ANTES</small><strong>100%</strong><span>→ carreira</span></div><div className="vs">/</div><div><small>DEPOIS</small><strong>CARREIRA</strong><span>+ governança<br/>+ contingência<br/>+ patrimônio</span></div></div>;
  if (kind === 'freedom') return <div className="freedom"><div><small>PRESSÃO FINANCEIRA</small><span>Preciso do próximo contrato.<br/>Preciso antecipar dinheiro.<br/>Preciso aceitar esta proposta.</span></div><div className="freedomDivider">→</div><div className="highlight"><small>BASE PATRIMONIAL</small><span>Possuo reserva.<br/>Possuo ativos.<br/>Possuo estrutura.</span></div></div>;
  if (kind === 'governance') return <Flow labels={['Investimento','Plano de capital','Liberações programadas','Desenvolvimento + patrimônio','Acompanhamento']} mode="stack"/>;
  if (kind === 'handoff') return <div className="handoff"><span>INVESTIDOR<small>inicia</small></span><i>↓</i><span>CARREIRA<small>cresce</small></span><i>↓</i><span>ATLETA<small>assume</small></span><i>↓</i><span>PATRIMÔNIO<small>acelera</small></span></div>;
  if (kind === 'index') return <div className="indexVisual"><div className="indexNumber">IPA<span>01</span></div><p>Índice de<br/><strong>Patrimonialização<br/>do Atleta</strong></p></div>;
  return <div className="endVisual"><div className="endLine"/><span>DESENVOLVER</span><span>PROTEGER</span><span>PATRIMONIALIZAR</span><span>ACOMPANHAR</span></div>;
}

function App() {
  const [active, setActive] = useState(0); const refs = useRef<(HTMLElement | null)[]>([]); const reduce = useReducedMotion();
  const go = (i: number) => { const next = Math.max(0, Math.min(chapters.length - 1, i)); refs.current[next]?.scrollIntoView({ behavior: reduce ? 'auto' : 'smooth' }); setActive(next); };
  useEffect(() => { const observer = new IntersectionObserver(es => es.forEach(e => { if (e.isIntersecting) setActive(Number((e.target as HTMLElement).dataset.index)); }), { threshold: .6 }); refs.current.forEach(r => r && observer.observe(r)); return () => observer.disconnect(); }, []);
  useEffect(() => { const key = (e: KeyboardEvent) => { if (['ArrowDown','ArrowRight',' '].includes(e.key)) { e.preventDefault(); go(active + 1); } if (['ArrowUp','ArrowLeft'].includes(e.key)) { e.preventDefault(); go(active - 1); } if (e.key.toLowerCase() === 'f') document.documentElement.requestFullscreen?.(); }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key); }, [active]);
  return <main className="app"><header className="topbar"><div className="brand"><a className="backToPortal" href="/">← TESES</a><img className="verossLogo" src="https://www.veross.com.br/img/logos/logo-veross.svg" alt="Veross"/><span className="deckIdentity"><b>CAPITAL PROTEGIDO</b><small>HOLOFOTE NO ATLETA</small></span></div><div className="topMeta">LUCAS SILVESTRE / 2026 <button onClick={() => document.documentElement.requestFullscreen?.()} aria-label="Tela cheia"><Maximize2 size={15}/></button></div></header><div className="progress"><i style={{ width: `${((active + 1) / chapters.length) * 100}%` }}/></div><div className="chapterCount">{String(active + 1).padStart(2,'0')} <span>/ {String(chapters.length).padStart(2,'0')}</span></div><div className="slides">{chapters.map((c, i) => <section key={i} data-index={i} ref={el => { refs.current[i] = el; }} className={`slide slide-${c.visual}`}><div className="slideGrid"><div className="copy"><motion.div initial={{ opacity: 0, y: reduce ? 0 : 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: false, amount: .5 }} transition={{ duration: .7 }}><div className="eyebrow">{c.eyebrow}</div><h1>{c.title}</h1>{c.body && <p>{c.body}</p>}</motion.div></div><motion.div className="visual" initial={{ opacity: 0, x: reduce ? 0 : 22 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: false, amount: .4 }} transition={{ duration: .8, delay: .08 }}><Visual kind={c.visual}/></motion.div></div><div className="slideFoot"><span>CAPITAL PROTEGIDO / DESENVOLVIMENTO DE ATLETAS</span></div></section>)}</div><nav className="controls"><button onClick={() => go(active - 1)} disabled={active === 0} aria-label="Anterior"><ArrowUp size={15}/></button><button onClick={() => go(active + 1)} disabled={active === chapters.length - 1} aria-label="Próximo"><ArrowDown size={15}/></button><span>↑ ↓ / espaço</span></nav></main>;
}
createRoot(document.getElementById('root')!).render(<App/>);



